### ISSUE TITLE
Отдельная лента "Поделился"

### ISSUE THREAD

**Issue by vadbars** [GolosChain/gip#11]
Предлагаю вынести все реблоги (репосты) в отдельную ленту.
Сейчас они зрительно почти не отличаются от авторских постов, что затрудняет чтение блогов.

Лента "Поделился" - по смыслу практически "закладки" или "избранное", появления которых на Голосе многие ждут.

**Comment by On1x** [comment]
Закладки и избранное - по-аналогии с соц сетями - это те посты, за которые отдал голос пользователь. Многие используют репост по прямому назначению - рассказать друзьям об интересном материале. Поэтому я против приравнивание репоста к закладкам - цели совершенно разные.

**Comment by serejandmyself** [comment]
Это должно быть в толстом, а не тут

**Comment by vadbars** [comment]
В толстом тоже есть https://github.com/GolosChain/tolstoy/issues/382
В таком случае здесь можно закрывать.
