### ISSUE TITLE
Улучшенная настраиваемая фильтрация постов по тегам и пользователям

### ISSUE THREAD

**Issue by Gutalean** [GolosChain/gip#16]
1) Чтобы можно было выбрать какие теги исключать из своей ленты (мне, к примеру, не интересны посты, содержащие тег #конкурс). 

2) Возможность сохранения настроенных фильтров под уникальными именами, для последующей быстрой смены, без необходимости повторной настройки.

3) Возможность фильтрации постов по репутации авторов, чтобы можно было отдельно читать контент от новичков и от гуру Голоса.

4) Возможность исключения репостов из ленты.

5) Рекомендательный сервис постов на основе сходства вкусов пользователей. Только открытый код и прозрачный механизм работы.

**Comment by serejandmyself** [comment]
Дубликат. Это относится к реп. tolstoy
