### ISSUE TITLE
Замена ссылки на руководство по Markdown

### ISSUE THREAD

**Issue by lokkie12** [GolosChain/gip#19]
При добавлении поста можно увидеть ссылку "Руководство по Markdown", которая ведет сюда https://guides.github.com/features/mastering-markdown/ Бьюсь об заклад, что большинство переходящих по ссылке сразу закрывают гитхаб.
Лучше, на мой взгляд, отсылать на русскоязычное и более понятное руководство от Онотоле https://golos.io/ru--golos/@on0tole/osnovy-oformleniya-postov-na-golose-polnyi-kurs-po-rabote-s-markdown

**Comment by serejandmyself** [comment]
Просьба перенести в tolstoy, это не касается репозитория GIP
