### ISSUE TITLE
Скрытие вывода технической информации из общей ленты - специальный тэг

### ISSUE THREAD

**Issue by vadbars** [GolosChain/gip#6]
Куда девать важные подробности, которые надо запротоколировать, но не обязательно выкладывать на широкое обозрение? Например, лотобот проводит лотереи и нужно фиксировать в БЧ данные для проверки честного розыгрыша. Но общую ленту сообщений не стоит засорять.

Нужен, наверное, специальный скрывающий тэг для такого рода сообщений.

**Comment by gropox** [comment]
Как вариант сделать, что-то вроде &lt;lj-cut&gt; тэга. В готовом тексте же просто ссылка при клике на которую открывается скрытый текст.

**Comment by serejandmyself** [comment]
Проблема в тегах, то что они "засоряют" подгрузку постов. Несмотря на новый набор АПИ, это не лучшее решение

**Comment by gropox** [comment]
@serejandmyself ну так любой тэг из существующих "засоряют" подгрузку. html, p, center. В чем проблема, если в тексте все, что после ```<cut>конкретика...```  заменить на что то вроде  
```
<details>
  <summary>Открыть</summary>
 конкретика
</details>
```

или просто разрешить этот html, сейчас эти тэги вырезаются на голосе. На github же работает

<details>
  <summary>Тыкните сюда, что бы попробовать</summary>
Это по моему даже поможет сократить трафик, если при загрузке ленты игнорировать содержимое тэга. Хотя честно говоря я не специалист. Возможно я и ошибаюсь.
 конкретика
</details>

**Comment by serejandmyself** [comment]
Секунду... О чем сейчас речь? Если речь о скрытии постов с тегом Х из общей ленты. То для этого уже есть набор тегов. Добавлять в этот список еще теги смысла нет. Чем больше информация сервер возвращает "скрытой" тем больше нагрузка на клиента. 

Если речь о другом, то просьба пояснить

**Comment by gropox** [comment]
Да, точно. Я подумал о другом.  Я подумал речь идет о контенте. Что бы в постах скрывать детальную информацию. Я так понял @vadbars, когда мы обсуждали с @vadbars это на голосе. Сорри.

К примеру пост lotobot пользователя сейчас выглядит так https://golos.io/ru--lotereya/@lotobot/lottery-round-finalizer-1492134747000

Хотелось бы скрыть таблицу с участниками и скрыть инфу, как происходили вычисления. Это сделало бы многие посты со статистикой более удобочитаемыми. 

<details>
<summary>Вычисления</summary>
Для вычисления победителя использовались следующие данные.

Блок анонса под номером 5107925.
Подпись делегата: 1f4a92c546951d9a41e04256c44b81a1d13c5f7b3757a979574144cba6370125442e5a3a7622b57af42eb82a05cf14ed11ccbd86df8065b0ca8111a46d0425467a

Блок на момент окончания раунда под номером 5117414.
Подпись делегата: 20226e86c35fbfd107147ed3d7601743861c42ec0f3890bee86377da90fb323b8227535b116c439d6a3ba944cff5b081cfd4cca62a06b092a2eadbd236e86119f1

Вычесленный keccak-256 хэш: 72e75f1c37b573209a3ada0d8454bfee200fceb40b490e8c8629196506557516

Проверить хэш можно здесь (ввести обе подписи одна за другой, без пробела)

Вычисленный счастливый номер 4

Проверить вычисления можно здесь.

Авторское вознагрождение составило 0.194 Голоса
</details>

**Comment by gropox** [comment]
Я тогда создам другое issue
